### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by hparcells** [WeAreDevs/material-clicker#25]
Milestones will give you rewards and Material. The point to get the next milestone will or should increase exponentially.

To-do:
- [x] Get it to work.
- [x] Add some basic milestones.
- [ ] Make it infinitely long.
- [x] Finish the UI, progress bar
- [x] Display past milestones
- [x] notification when you get a new milestone

**Comment by hparcells** [comment]
Should we include a button that says Claim, and you must press that to claim it, or do just get the rewards automatically, and it just displays a snackbar.

**Comment by imdaveead** [comment]
> Should we include a button that says Claim, and you must press that to claim it, or do just get the rewards automatically, and it just displays a snackbar.

I thought about that, but don't really feel like it now.
